
insert into Car (LICENCE_PLATE, MAKE, MODEL, YEAR_OF_MADE, BODY_TYPE, FUEL_TYPE) values ('1N6AF0', 'Chevrolet', 'Aveo', 2004,                   'sedan', 'diesel');
insert into Car (LICENCE_PLATE, MAKE, MODEL, YEAR_OF_MADE, BODY_TYPE, FUEL_TYPE) values ('JN8AS5', 'Acura', 'TL', 2009,                             'sedan', 'petrol');
insert into Car (LICENCE_PLATE, MAKE, MODEL, YEAR_OF_MADE, BODY_TYPE, FUEL_TYPE) values ('KMHDB8', 'Dodge', 'Avenger', 1999,                        'sedan', 'petrol');
insert into Car (LICENCE_PLATE, MAKE, MODEL, YEAR_OF_MADE, BODY_TYPE, FUEL_TYPE) values ('5LMJJ3', 'Acura', 'CL', 1998,                          'sedan', 'petrol');
insert into Car (LICENCE_PLATE, MAKE, MODEL, YEAR_OF_MADE, BODY_TYPE, FUEL_TYPE) values ('WDDGF4', 'Mitsubishi', 'Montero', 2006,                'sedan', 'petrol');
insert into Car (LICENCE_PLATE, MAKE, MODEL, YEAR_OF_MADE, BODY_TYPE, FUEL_TYPE) values ('1N6AD0', 'Mitsubishi', 'Eclipse', 1996,                'wagon', 'petrol');
insert into Car (LICENCE_PLATE, MAKE, MODEL, YEAR_OF_MADE, BODY_TYPE, FUEL_TYPE) values ('1G6AK5', 'Ford', 'F250', 2000,                            'wagon', 'diesel');
insert into Car (LICENCE_PLATE, MAKE, MODEL, YEAR_OF_MADE, BODY_TYPE, FUEL_TYPE) values ('4T1BF1', 'Acura', 'TSX', 2005,                            'sedan', 'diesel');
insert into Car (LICENCE_PLATE, MAKE, MODEL, YEAR_OF_MADE, BODY_TYPE, FUEL_TYPE) values ('3GYFNE', 'Buick', 'Park Avenue', 1994,                 'sedan', 'petrol');
insert into Car (LICENCE_PLATE, MAKE, MODEL, YEAR_OF_MADE, BODY_TYPE, FUEL_TYPE) values ('WBAGN6', 'Cadillac', 'Escalade ESV', 2011,             'sedan', 'diesel');
insert into Car (LICENCE_PLATE, MAKE, MODEL, YEAR_OF_MADE, BODY_TYPE, FUEL_TYPE) values ('1FTMF1', 'BMW', '530', 2007,                           'sedan', 'diesel');
insert into Car (LICENCE_PLATE, MAKE, MODEL, YEAR_OF_MADE, BODY_TYPE, FUEL_TYPE) values ('3N6CM0', 'Chevrolet', 'HHR', 2009,                     'sedan', 'diesel');
insert into Car (LICENCE_PLATE, MAKE, MODEL, YEAR_OF_MADE, BODY_TYPE, FUEL_TYPE) values ('KNDJT2', 'Subaru', 'Justy', 1991,                      'wagon', 'diesel');
insert into Car (LICENCE_PLATE, MAKE, MODEL, YEAR_OF_MADE, BODY_TYPE, FUEL_TYPE) values ('1FTEW1', 'Porsche', '911', 1996,                       'wagon', 'petrol');
insert into Car (LICENCE_PLATE, MAKE, MODEL, YEAR_OF_MADE, BODY_TYPE, FUEL_TYPE) values ('WAUMR4', 'Chevrolet', 'Tahoe', 2010,                   'sedan', 'petrol');
insert into Car (LICENCE_PLATE, MAKE, MODEL, YEAR_OF_MADE, BODY_TYPE, FUEL_TYPE) values ('3D7TT2', 'Mercedes-Benz', 'E-Class', 1997,             'wagon', 'petrol');
insert into Car (LICENCE_PLATE, MAKE, MODEL, YEAR_OF_MADE, BODY_TYPE, FUEL_TYPE) values ('1G4GF5', 'Pontiac', 'Grand Am', 1990,                  'wagon', 'petrol');
insert into Car (LICENCE_PLATE, MAKE, MODEL, YEAR_OF_MADE, BODY_TYPE, FUEL_TYPE) values ('1GYS4C', 'GMC', 'Sierra 3500HD', 2006,                 'wagon', 'petrol');
insert into Car (LICENCE_PLATE, MAKE, MODEL, YEAR_OF_MADE, BODY_TYPE, FUEL_TYPE) values ('2G61W5', 'Ford', 'Taurus', 1997,                       'sedan', 'diesel');
insert into Car (LICENCE_PLATE, MAKE, MODEL, YEAR_OF_MADE, BODY_TYPE, FUEL_TYPE) values ('1G6DG8', 'Aston Martin', 'Virage', 2011,               'wagon', 'diesel');